version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: social_network_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-social_network}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - social_network_network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: social_network_redis
    ports:
      - "6379:6379"
    networks:
      - social_network_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social_network_backend
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-social_network}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES:-3600}
      - JWT_REFRESH_TOKEN_EXPIRES=${JWT_REFRESH_TOKEN_EXPIRES:-2592000}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-true}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - social_network_network
    volumes:
      - ./backend:/app
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 run:app

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social_network_frontend
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000/api}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - social_network_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: social_network_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - social_network_network

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: social_network_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}

volumes:
  postgres_data:

networks:
  social_network_network:
    driver: bridge
