"""Initial migration for social network with PostgreSQL

Revision ID: 7e5076550f6c
Revises: 
Create Date: 2025-09-15 17:51:38.440578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e5076550f6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media', sa.JSON(), nullable=True))
        batch_op.drop_column('ai_generated_hashtags')
        batch_op.drop_column('longitude')
        batch_op.drop_column('location_name')
        batch_op.drop_column('ai_generated_description')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('social_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_flags', sa.JSON(), nullable=True))
        batch_op.alter_column('action_taken',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('moderator_notes')
        batch_op.drop_column('ai_analysis')

    with op.batch_alter_table('social_users', schema=None) as batch_op:
        batch_op.alter_column('gramps_person_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('gramps_tree_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('social_users_gramps_person_id_key'), type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('first_name')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('social_users_gramps_person_id_key'), ['gramps_person_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('gramps_tree_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('gramps_person_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('social_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('moderator_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('action_taken',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('ai_flags')

    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_generated_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_generated_hashtags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('media')

    # ### end Alembic commands ###
